
trigger:
  - main

variables:
  - name: port
    value: 8080
  - name: max_clients
    value: 4

pool: default
strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'server.py'
      arguments: '$(port) $(max_clients)'
      workingDirectory: '/Lab-01/src/server/'
      failOnStderr: true

  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'client.py'
      arguments: '127.0.0.1:$(port) note1.txt'
      workingDirectory: '/Lab-01/src/client/'
      failOnStderr: true

